### ISSUE TITLE
Live dynamic content

### ISSUE THREAD

**Issue by Serveurperso** [chrisdavies/tlite#20]
Hi,

Can I use it to display live changing dynamic data like bandwidth etc... (from my Socket.IO live client ) ?

(no ads) https://www.serveurperso.com/?page=robots

Pascal

**Comment by chrisdavies** [comment]
Woah. That's a cool site!

You can't do it without hacks. Basically, you'd have to grab the tooltip element and manipulate it directly:

`document.querySelector('.tlite-visible').textContent = 'Shazm!';`

Or, instead of document, you can use the element that contains the tooltip you want to manipulate.

**Comment by Serveurperso** [comment]
Thanks, outch I must open another case for touch compatibility (or it's the same to use manual everywhere ???) it need a automatic manual mode for smartphone device and standard for PC.
